### ISSUE TITLE
Mistake mod-anticheat

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/mod-anticheat#86] opened 2022-08-23 07:19 UTC
### Current Behaviour

How can this be fixed?
![2022-08-23_10-05-51](https://user-images.githubusercontent.com/98691968/186095692-7b737c28-3d89-47cb-86cd-6d375b2ae1db.png)

[1136] Column count doesn't match value count at row 1
Unhandled MySQL errno 1136. Unexpected behaviour possible.
SQL(p): INSERT INTO account_banned VALUES (3, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+0, Server, Anti cheat module Auto Banned Account for Reach Cheat Threshhold, 1)
[ERROR]: [1062] Duplicate entry '3-1661238008' for key 'PRIMARY'

### Expected Blizzlike Behaviour

no

### Source

no

### Steps to reproduce the problem

After the anti-cheat is triggered, such an error appears, how can it be fixed?

### Extra Notes

no

### AC rev. hash/commit

AzerothCore

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-anticheat

**Comment by acidmanifesto** [comment] 2022-08-23 10:53
Is your cire up todate? What revision of azerothcore and the the anticheat you are on? What changes did you make to the anticheat?  If you did not make any changes, what changes did you do to the core? I can not repeoduce this issue.

**Comment by MegaserverRU** [comment] 2022-08-23 11:36
> Is your core up todate? What revision of azerothcore and the the anticheat you are on? What changes did you make to the anticheat? If you did not make any changes, what changes did you do to the core? I can not repeoduce this issue.

I didn't make any changes to the kernel, the last kernel update was yesterday and the anti-cheat update was also yesterday. Today I decided to check the anti-cheat for performance downloaded the cheat program WoWEmuHacker v5.0.5.4 Final
I turned on the flight and speed mode, the anti-cheat worked well, issued a ban to the character, but after the ban I'm in worldserver.exe I saw this error, it was marked in red, so I decided to clarify, is it possible to fix it somehow?

**Comment by acidmanifesto** [comment] 2022-08-23 11:45
at current i recieve no such issue. I can not reproduce.
![image](https://user-images.githubusercontent.com/16887899/186149577-28b4675b-e2c1-4e38-8297-5e9585add7f9.png)
what sql version are you using currently?
Banning is done thru the same function as the .player ban gm command.
The anticheat makes no direct modification to the account_banned table itself.

**Comment by MegaserverRU** [comment] 2022-08-23 11:48
version 8.0 of sql

**Comment by acidmanifesto** [comment] 2022-08-23 12:05
> version 8.0 of sql

Does it do this all the time?
The error would suggest it is banning a character that is... already banned?

**Comment by MegaserverRU** [comment] 2022-08-23 12:13
Yes, this error occurs constantly on different accounts

**Comment by MegaserverRU** [comment] 2022-08-23 12:14
> Yes, this error occurs constantly on different accounts

I will try to delete everything now and fill in the SQL files again

**Comment by acidmanifesto** [comment] 2022-08-23 13:05
> > Yes, this error occurs constantly on different accounts
> 
> I will try to delete everything now and fill in the SQL files again

Let me know how it goes. Im still trying to see if this is going to be a core issue or not.

**Comment by MegaserverRU** [comment] 2022-08-23 18:13
The error remains 1 time if the SQL database is clean account_banned then it gives the usual error that I showed you earlier.
![2022-08-23_10-05-51](https://user-images.githubusercontent.com/98691968/186232745-bf1983c7-6971-42b5-807b-59d114c1412c.png)

then when banned accounts appear and you change from 1 to 0 thereby removing the account ban, a server crash begins to appear in SQL account_banned
![2022-08-23_21-05-35](https://user-images.githubusercontent.com/98691968/186233188-b643578f-d379-4dd5-9b66-33a035ae7322.png)

But actually the crash itself
![2022-08-23_21-04-15](https://user-images.githubusercontent.com/98691968/186233330-169b0f2f-952b-47ef-8c61-5283bccd4654.png)

**Comment by MegaserverRU** [comment] 2022-08-23 18:17
Maybe you will give me your anti-cheat SQL files, I will fill them in and recheck them

**Comment by MegaserverRU** [comment] 2022-08-23 18:21
Here's another error that came out
![2022-08-23_21-20-19](https://user-images.githubusercontent.com/98691968/186234695-6112307b-bd13-463a-b8a5-8000b45f3b4e.png)

**Comment by acidmanifesto** [comment] 2022-08-23 23:23
> The error remains 1 time if the SQL database is clean account_banned then it gives the usual error that I showed you earlier. ![2022-08-23_10-05-51](https://user-images.githubusercontent.com/98691968/186232745-bf1983c7-6971-42b5-807b-59d114c1412c.png)
> 
> then when banned accounts appear and you change from 1 to 0 thereby removing the account ban, a server crash begins to appear in SQL account_banned ![2022-08-23_21-05-35](https://user-images.githubusercontent.com/98691968/186233188-b643578f-d379-4dd5-9b66-33a035ae7322.png)
> 
> But actually the crash itself ![2022-08-23_21-04-15](https://user-images.githubusercontent.com/98691968/186233330-169b0f2f-952b-47ef-8c61-5283bccd4654.png)

the issue is that the id and the bandate are primary key collumns. They can not be duplicated. Al though u can have multiple id being 1, the bandate needss to be different, if at any time the id collumn and bandate have a duplicate, it will error out. It "SHOULD" be impossible to havea duplicate of having the same ban date (which is done in UNIX) with the player ID.
However this will be a core issuea and handling as it uses the sBan. The account_banned would not be anything related to the anticheat as it is a table exsistent with the azerothcore it self. https://www.azerothcore.org/wiki/account_banned

**Closed** 2022-08-23 23:23 UTC
Labels: Evaulating, Core Issue

**Comment by MegaserverRU** [comment] 2022-08-24 06:56
I don't understand you. What do I need to do to avoid such mistakes?
