### ISSUE TITLE
anticheat

### ISSUE THREAD

**Issue by blakcnightt** [azerothcore/mod-anticheat#25] opened 2021-02-18 15:33 UTC
Hello
I installed mod-anti cheat
But it can not analyze all hacks
I will send you 2 examples of hacks that all players use
As well as a video showing how to use hacks
I asked you

fix hack teleport
And
Like hack fly that when
The player wants to use the kick server
hack speed and so on
We can set that
When the player wants to use
Kick from the server
thank you

- [ ] http://3x3x5.ir/dl/2021/02/hack-teleport.mp4

[The Hitchhiker's Hack 3.3.5.zip](https://github.com/azerothcore/mod-anticheat/files/6003959/The.Hitchhiker.s.Hack.3.3.5.zip)
[WowAdminPanel.zip](https://github.com/azerothcore/mod-anticheat/files/6003961/WowAdminPanel.zip)

(I have set that if Players Fly Hack
Use
kick
This is also the case for speed
it is good)

like this :
https://youtu.be/xEN3hWMn060

**Comment by Helias** [comment] 2021-02-18 16:53
duplicate of https://github.com/azerothcore/mod-anticheat/issues/26

**Closed by Helias** 2021-02-18 16:53 UTC
