### ISSUE TITLE
use ".pinfo" command,server crash

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-anticheat#24] opened 2020-12-17 10:12 UTC
when GM uses the. pinfo command, the server crash...

 AzerothCore revision            : 4cb0c9fc0042+ 2020-12-10 05:57:54 +0000 (master branch)
OS:ubuntu 18.04
Module:mod-anticheat

**Comment by FrancescoBorzi** [comment] 2020-12-18 09:24
thanks @mpfans for your feedback, moving to the right repository

**Comment by Helias** [comment] 2021-02-18 18:35
cannot reproduce on 2e6f78bdddbc84a1950aaec0865a689efa9fcde4

**Comment by mpfans** [comment] 2021-03-31 01:03
anticheat :https://github.com/azerothcore/mod-anticheat/commit/10659d66423ad11e3f0761f0d1fe36f988568110  
ac core :877e394e04e13662554f8cce663bea1c646a98d2

Still crash....

**Comment by mpfans** [comment] 2021-03-31 01:03
@Helias

**Comment by acidmanifesto** [comment] 2022-02-10 15:18
issue is no longer occuring with current revision being tested [3bd91e1](https://github.com/azerothcore/mod-anticheat/commit/3bd91e16c4515543817896ded8098ac7bb45bcd3)

**Closed by acidmanifesto** 2022-02-10 15:18 UTC
